name: Terraform self hosted runner Deployment
on:
  push:
    branches:
      - main
      - feature

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform self hosted runner Deployment
    runs-on:
      - self-hosted
      - windows
      - x64

    defaults:
      run:
        shell: powershell
        working-directory: .

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Azure CLI
        run: |
          Write-Host "AZURE CLI VERSION"
          az version

      - name: Check Azure Login
        run: |
          Write-Host "CURRENT WINDOWS USER"
          whoami

          Write-Host "AZURE ACCOUNT"
          az account show --output table

      - name: Check Terraform
        run: |
          Write-Host "TERRAFORM PATH"
          where.exe terraform

          Write-Host "TERRAFORM VERSION"
          terraform version

      - name: Check Terraform Files
        run: |
          Write-Host "CURRENT DIRECTORY"
          Get-Location

          Write-Host "TERRAFORM FILES"
          Get-ChildItem -Path . -Filter *.tf

      - name: Terraform Init
        run: |
          Write-Host "TERRAFORM INIT"
          terraform init

      - name: Terraform Validate
        run: |
          Write-Host "TERRAFORM VALIDATE"
          terraform validate

      - name: Terraform Plan
        run: |
          Write-Host "TERRAFORM PLAN"
          terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          Write-Host "TERRAFORM APPLY"
          terraform apply -auto-approve
